-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at http://mozilla.org/MPL/2.0/.

--[[
# Validates the auth_lastx alerts
--]]

require "string"

-- results table corresponds to input test table and analysis configuration
local results = {
    {
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR picard ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-picard@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR picard ssh auth bastion.host track:[192.168.1.4]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-picard@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[216.160.83.56] (Milton, US)",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[216.160.83.56] (Milton, US)",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    {
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[216.160.83.56] (Milton, US)",
            recipients = { "<captainkirk@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n" ..
                "WARNING, unacceptable drift"
        },
        {
            summary    = "riker ssh auth bastion.host track:[216.160.83.56] (Milton, US)",
            recipients = { "<captainkirk@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n" ..
                "WARNING, unacceptable drift"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[216.160.83.56] (Milton, US)",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    {
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.1]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.4]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.5]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.1]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.5]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    {
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.2+publickey]",
            irctarget  = "irc.server#target",
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2+publickey]",
            irctarget  = "irc.server#target",
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.2+password]",
            irctarget  = "irc.server#target",
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    {
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.1]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            irctarget  = "irc.server#target",
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            irctarget  = "irc.server#target",
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            irctarget  = "irc.server#target",
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            irctarget  = "irc.server#target",
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
    },
    {
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker awsconsole auth 999999999999 track:[10.0.0.1]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[10.0.0.1]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    {
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker duopull auth admin_login track:[10.0.0.1]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "riker ssh auth bastion.host track:[10.0.0.1]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    {
        {
            summary    = "LASTX_NEWATTR worf ssh auth bastion.host track:[192.168.1.1]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR worf ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "worf ssh auth bastion.host track:[192.168.1.2]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR riker ssh auth bastion.host track:[192.168.1.3]",
            recipients = { "<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-riker@moz-svc-ops.pagerduty.com>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "LASTX_NEWATTR geordi ssh auth bastion.host track:[192.168.1.4]",
            recipients = { "<engineering@uss-enterprise>", "<laforge@main-engineering.uss-enterprise>" },
            payload = "^Escalation flag set, authentication with new tracking attributes\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "geordi ssh auth bastion.host track:[192.168.1.4]",
            recipients = { "<engineering@uss-enterprise>" },
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
    }
}

local cnt = { 1, 1, 1, 1, 1, 1, 1, 1 }

function process_message()
    local summary    = read_message("Fields[summary]") or error("no summary field")
    local dflt_recip = read_message("Fields[email.recipients]")
    local user_recip = read_message("Fields[email.recipients]", 0, 1)
    local irc_targ   = read_message("Fields[irc.target]")
    local payload    = read_message("Payload")
    local logger     = read_message("Logger")

    local tnum = tonumber(string.match(logger, "analysis.auth_lastx_(%d)"))
    if not tnum then return 1, "invalid logger value" end

    local comp = results[tnum][cnt[tnum]]
    if summary ~= comp.summary then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], summary))
    end
    if comp.recipients and comp.recipients[1] ~= dflt_recip then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], dflt_recip))
    end
    if comp.recipients and #comp.recipients > 1 and comp.recipients[2] ~= user_recip then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], user_recip or "nil"))
    end
    if comp.recipients and #comp.recipients == 1 and user_recip then
        error(string.format("test:%d cnt:%d unexpected user recipient", tnum, cnt[tnum]))
    end
    if comp.irctarget and comp.irctarget ~= irc_targ then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], irc_targ))
    end
    if not string.match(payload, comp.payload) then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], payload))
    end

    cnt[tnum] = cnt[tnum] + 1

    return 0
end


function timer_event()
    for i,v in ipairs(cnt) do
        assert(v - 1 == #results[i], string.format("test:%d %d out of %d tests ran", i, v - 1, #results[i]))
    end
end
