-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at http://mozilla.org/MPL/2.0/.

--[[
# Validates the moz_security_sshd_login alerts
--]]

require "string"

-- results table corresponds to input test table and analysis configuration
local results = {
    { -- test case 1, standard configuration
        {
            summary    = "trink bastion login bastion.host from 192.168.1.1",
            recipients = {"<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-trink@moz-svc-ops.pagerduty.com>"},
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "trink bastion login bastion.host from 192.168.1.2 (Mountain View, US)",
            recipients = {"<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-trink@moz-svc-ops.pagerduty.com>"},
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    { -- test case 2, no user recipient
        {
            summary    = "trink bastion login bastion.host from 192.168.1.1",
            recipients = {"<foxsec-dump+OutOfHours@mozilla.com>"},
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "trink bastion login bastion.host from 192.168.1.2 (Mountain View, US)",
            recipients = {"<foxsec-dump+OutOfHours@mozilla.com>"},
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    { -- test case 3, delay recipient
        {
            summary    = "trink bastion login bastion.host from 192.168.1.1",
            recipients = {"<captainkirk@mozilla.com>"},
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\nWARNING"
        },
        {
            summary    = "trink bastion login bastion.host from 192.168.1.2 (Mountain View, US)",
            recipients = {"<captainkirk@mozilla.com>"},
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\nWARNING"
        },
        {
            summary    = "trink bastion login bastion.host from 192.168.1.1",
            recipients = {"<foxsec-dump+OutOfHours@mozilla.com>", "<manatee-trink@moz-svc-ops.pagerduty.com>"},
            payload = "^Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    },
    { -- test case 4, drop delayed messages
    },
}

local cnt = {1, 1, 1, 1}

function process_message()
    local summary    = read_message("Fields[summary]") or error("no summary field")
    local dflt_recip = read_message("Fields[email.recipients]") or error("no email recipients")
    local user_recip = read_message("Fields[email.recipients]", 0, 1)
    local payload    = read_message("Payload")
    local logger     = read_message("Logger")

    local tnum = tonumber(string.match(logger, "analysis.sshd_login_monitor_(%d)"))
    if not tnum then return 1, "invalid logger value" end

    local comp = results[tnum][cnt[tnum]]
    if summary ~= comp.summary then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], summary))
    end
    if comp.recipients[1] ~= dflt_recip then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], dflt_recip))
    end
    if #comp.recipients > 1 and comp.recipients[2] ~= user_recip then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], user_recip or "nil"))
    end
    if #comp.recipients == 1 and user_recip then
        error(string.format("test:%d cnt:%d unexpected user recipient", tnum, cnt[tnum]))
    end
    if not string.match(payload, comp.payload) then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], payload))
    end


    cnt[tnum] = cnt[tnum] + 1

    return 0
end


function timer_event()
    for i,v in ipairs(cnt) do
        assert(v - 1 == #results[i], string.format("test:%d %d out of %d tests ran", i, v - 1, #results[i]))
    end
end
