-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at http://mozilla.org/MPL/2.0/.

require "string"

-- results table corresponds to input test table and analysis configuration
local results = {
    {
        {
            summary    = "AUTH_ANY riker ssh auth bastion.host src 192.168.1.2",
            recipients = { "<picard@mozilla.com>" },
            payload = "^Authentication to host configured to alert on any\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        },
        {
            summary    = "AUTH_ANY riker ssh auth bastion.host src 216.160.83.56 (Milton, US)",
            recipients = { "<picard@mozilla.com>" },
            payload = "^Authentication to host configured to alert on any\n" ..
                "Generated by integration_test, event timestamp %d+-%d+-%d+ %d+:%d+:%d+\n$"
        }
    }
}

local cnt = { 1 }

function process_message()
    local summary    = read_message("Fields[summary]") or error("no summary field")
    local dflt_recip = read_message("Fields[email.recipients]")
    local payload    = read_message("Payload")
    local logger     = read_message("Logger")

    local tnum = tonumber(string.match(logger, "analysis.auth_any_(%d)"))
    if not tnum then return 1, "invalid logger value" end

    local comp = results[tnum][cnt[tnum]]
    if summary ~= comp.summary then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], summary))
    end
    if comp.recipients and comp.recipients[1] ~= dflt_recip then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], dflt_recip))
    end
    if not string.match(payload, comp.payload) then
        error(string.format("test:%d cnt:%d %s", tnum, cnt[tnum], payload))
    end

    cnt[tnum] = cnt[tnum] + 1

    return 0
end


function timer_event()
    for i,v in ipairs(cnt) do
        assert(v - 1 == #results[i], string.format("test:%d %d out of %d tests ran", i, v - 1, #results[i]))
    end
end
